# Configuration file for Custom Sorter Program

# Input folder for testing
input_folders:  
  #- 'D:\custom_sorter\files needed\test'
  - '' #insert name of folder here. Add as many folders in the input folder as you want.


# Metadata key for sorting by metadata (if applicable)
metadata_key: "model"

#Note - if sorting by boolean value keys (true/false) it currently sorts into a folder with that value "true" or "false" -- you probably won't want to sort by this metadata_key until we fix this issue. But you can sort by any other item in your metadata. 

sort_methods: ["metadata"] #metadata, orientation, resolution
metadata_keys: ["model"] #metadata fields like model, steps, seed, etc. Use commas to seperate. Folders are created in the order used.


# Whether to move files to the output folder or organize them in place
use_output_folder: false

# Output folder where sorted files will be moved
output_folder: "D:/custom_sorter/files needed/test/test_output"

# Resolution-based folder categories (adjust as needed)
resolution_folders:
  superlow: "0x0"
  lores: "640x960"
  medres: "960x1440"
  hires: "1080x1920"
  superhigh: "99999x99999"

# Enable dynamic thresholds for automatic superlow/superhigh assignment
dynamic_thresholds: false

# Set to true to enable .json metadata file creation (default is now false unless changed below)
save_metadata_json: false  #

# "auto" dynamically selects thread count based on drive type: uses 8 threads for SSDs, 3 threads for HDDs. 
# You can also manually set this to a specific number (e.g. 4, 6, 12) to control the number of threads used for file moves.
file_move_threads: "auto" 

#Folders that don't have flags (from previous sorting) will be processed, if false, it will only sort the top level folder.
include_subfolders: true
